### ISSUE TITLE
Artemis Broker image is not exposing any Ports

### ISSUE THREAD

**Issue by hguerrero** [arkmq-org/arkmq-org-broker-image#15]
**Describe the bug**
When running the resulting container image, there is no default port exposed

**To Reproduce**
docker run -P container-image

**Platform (please complete the following information):**
 - OS: Mac OSX

**Expected behavior**
The container should expose the default ports.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by tlbueno** [comment]
Added default broker ports into pr: https://github.com/artemiscloud/activemq-artemis-broker-image/pull/33

**Comment by tlbueno** [comment]
closing this as https://github.com/artemiscloud/activemq-artemis-broker-image/pull/33 was merged
