### ISSUE TITLE
expose the ability to use broker properties for extra configuration

### ISSUE THREAD

**Issue by andytaylor** [arkmq-org/arkmq-org-broker-image#17]
Passing a parameter AMQ_PROPERTIES which is a comma separated list of broker properties will create a broker.properties file in the etc dir that the broker will load

**Comment by tlbueno** [comment]
After discussed this one with @brusdev, I am closing it as it is possible to set the broker properties by setting the JAVA_ARGS_APPEND environment variables and binding a properties file from the host, ie:
```
docker run -it --rm --name artemis -e AMQ_USER=admin -e AMQ_PASSWORD=admin -e JAVA_ARGS_APPEND='-Dbroker.properties=/opt/amq/broker.properties' -P -v /tmp/broker.properties:/opt/amq/broker.properties activemq-artemis-broker:latest
```
