### ISSUE TITLE
launch.sh does not recognize previously-created broker directories

### ISSUE THREAD

**Issue by Botje** [arkmq-org/arkmq-org-broker-image#23]
**Describe the bug**
[Line 15 of launch.sh](https://github.com/artemiscloud/activemq-artemis-broker-image/blob/main/modules/activemq-artemis-install/added/launch.sh#L15) is supposed to prevent the broker from running its initial configuration again, but it tests for the directory `BROKER` while line 39 of the same script creates a lower-case directory `broker`

**To Reproduce**
1. Run the image with `/home/jboss` mounted to a Kubernetes volume or host directory
2. Run the image again. The broker is reconfigured instead of using the configuration present in the volume.

**Platform (please complete the following information):**
 - OS: [e.g. Fedora] macOS
 - Version [e.g. 32] 13.0.1
 - CEKit version [e.g. 3.5.0] 4.5.0
 - Container build tool [e.g. podman] Docker, although I used prebuilt images from quay.io

**Comment by brusdev** [comment]
@Botje your analysis LGTM,  are you planning to create a PR to fix this bug?
