### ISSUE TITLE
Add PR commit message check to workflow

### ISSUE THREAD

**Issue by gaohoward** [arkmq-org/arkmq-org-broker-image#25]
**Is your feature request related to a problem? Please describe.**
Add check on commit messages of PR to make sure each begin with a issue number
[#nnn] or [NO-ISSUE]

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by tlbueno** [comment]
I am closing this issue as it is already implemented in https://github.com/artemiscloud/activemq-artemis-broker-image/commit/1a4647b1e62bc7c5fb381c31e962619c1dacb99b
