### ISSUE TITLE
Cannot initialize queue:Function not implemented

### ISSUE THREAD

**Issue by sbmaggarwal** [arkmq-org/arkmq-org-broker-image#30]
**Describe the bug**
Not able to launch the Basic Broker Image on Mac Apple M1 Pro Ventura 13.4.

**To Reproduce**
1. Get Docker running
2. Use this command:
```
docker run -e AMQ_USER=artemisuser -e AMQ_PASSWORD=artemispwd --name project-artemis --platform linux/x86_64 -p 80:8161 -p 61616:61616 quay.io/artemiscloud/activemq-artemis-broker:dev.latest
```

**Platform (please complete the following information):**
 - Mac Apple M1 Pro 
 - Ventura 13.4
 - Docker

**Expected behavior**
Above command should deploy the image on the [tutorial](https://artemiscloud.io/docs/tutorials/deploybasicimage/).

**Screenshots**
![Screenshot 2023-06-14 at 07 47 34](https://github.com/artemiscloud/activemq-artemis-broker-image/assets/6919017/3d39c13c-97ad-41a3-9ea9-53213b83966e)

**Additional context**
The error during `docker run` is:
```
Cannot initialize queue:Function not implemented
```

**Comment by brusdev** [comment]
@sbmaggarwal the M1 is an ARM processor, not an x86 processor, could you try `--platform linux/arm64`:
```
docker run -e AMQ_USER=artemisuser -e AMQ_PASSWORD=artemispwd --name project-artemis --platform linux/arm64 -p 80:8161 -p 61616:61616 quay.io/artemiscloud/activemq-artemis-broker:dev.latest
```

**Comment by sbmaggarwal** [comment]
That was silly of me, thank you!
