### ISSUE TITLE
Update of python version 2 to 3

### ISSUE THREAD

**Issue by tlbueno** [arkmq-org/arkmq-org-broker-image#31]
Update of python version 2 to 3 package as part of the https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/issues/51 enhancement

**Comment by brusdev** [comment]
Could this upgrade cause any issues to https://github.com/artemiscloud/activemq-artemis-broker-init-image?

**Comment by tlbueno** [comment]
Good point @brusdev. I will test it because I just tested the broker-kubernetes-image. As far as I see the broker-init-image do not use python version 2 since yacfg works with python3 and I didn't find any reference in broker-init-image for python2 binary. Once I test it properly I will report here.

**Comment by tlbueno** [comment]
@brusdev, the broker-init-image don´t need to be updated.
Currently broker-init-image has python3.8 and I am using the same in the broker-image. 
To summarize we have 2 PR related to this change:
1 - This one
2 - https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/pull/82 (already merged)

**Comment by tlbueno** [comment]
closing this issue as https://github.com/artemiscloud/activemq-artemis-broker-image/pull/32 was merged
