### ISSUE TITLE
Provide images 1.0.26 and artemis.2.33.0 to quay.io

### ISSUE THREAD

**Issue by turing85** [arkmq-org/arkmq-org-broker-image#47]
`activemq-artemis` version `2.33.0` [has been released on 2024-03-19 (`github.com`)](https://github.com/apache/activemq-artemis/releases/tag/2.33.0). Thus, it would be nice to generate corresponding images based on this version.

**Comment by brusdev** [comment]
ArtemisCloud broker container images based on Apache ActiveMQ Artemis 2.33.0 are available:
quay.io/artemiscloud/activemq-artemis-broker:1.0.26
quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.25
quay.io/artemiscloud/activemq-artemis-broker.init:1.0.26

The same broker container images are also available with the artemis tag:
quay.io/artemiscloud/activemq-artemis-broker:artemis.2.33.0
quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.33.0
quay.io/artemiscloud/activemq-artemis-broker.init:artemis.2.33.0

ArtemisCloud broker container snapshot images based are built every day on the latest Apache ActiveMQ Artemis snapshot to test new features and bug fixes before an official Apache ActiveMQ Artemis release:
quay.io/artemiscloud/activemq-artemis-broker:snapshot
quay.io/artemiscloud/activemq-artemis-broker-kubernetes:snapshot
quay.io/artemiscloud/activemq-artemis-broker.init:snapshot

**Comment by turing85** [comment]
@brusdev thanks a lot for the quick response!
