### ISSUE TITLE
Extra Argument http-host can't be overridden

### ISSUE THREAD

**Issue by jorgecastro05** [arkmq-org/arkmq-org-broker-image#50]
**Describe the bug**
Executing the image always auto assign an IP Address of the local network or the internal docker network, and can't be overridden using the AMQ_EXTRA_ARGS option.

For example: 
`podman run -it --rm -p 5672:5672 -p 8161:8161 -e AMQ_USER=admin -e AMQ_PASSWORD=password --name artemis quay.io/artemiscloud/activemq-artemis-broker:artemis.2.37.0`

Gives the output (at end)

```
ole(s): "admin" role principal classes: "org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal"
2024-10-25 22:52:42,001 INFO  [io.hawt.web.auth.LoginRedirectFilter] Hawtio loginRedirectFilter is using 1800 sec. HttpSession timeout
2024-10-25 22:52:42,012 INFO  [org.apache.activemq.artemis] AMQ241001: HTTP Server started at http://192.168.10.106:8161
2024-10-25 22:52:42,012 INFO  [org.apache.activemq.artemis] AMQ241002: Artemis Jolokia REST API available at http://192.168.10.106:8161/console/jolokia
2024-10-25 22:52:42,012 INFO  [org.apache.activemq.artemis] AMQ241004: Artemis Console available at http://192.168.10.106:8161/console
```

**To Reproduce**

`podman run -it --rm -p 5672:5672 -p 8161:8161 -e AMQ_USER=admin -e AMQ_PASSWORD=password -e AMQ_EXTRA_ARGS='--http-host=0.0.0.0' --name artemis quay.io/artemiscloud/activemq-artemis-broker:artemis.2.37.0`

The output of the command is:
```
Creating Broker with args --user XXXXX --password XXXXX --role admin --name broker --allow-anonymous --http-host 192.168.10.106 --host 192.168.10.106   --force --http-host=0.0.0.0
option '--http-host' (<httpHost>) should be specified only once

Usage: artemis help [<args>...]
use 'help <command>' for more information
      [<args>...]
```

**Platform (please complete the following information):**
 - OS: Fedora
 - Version 40
 - CEKit version Not Used
 - Container build tool: podman

**Expected behavior**
the AMQ_EXTRA_ARGS option with the param `http-host` should be overriden for example to assign a IP Address like 127.0.0.1 or localhost.

**Comment by brusdev** [comment]
The AMQ_EXTRA_ARGS environment variable doesn't allow to override the default args. You can use webconfig system property to overwrite the artemis binding uri and `--relax-jolokia` to relax the jolokia checks, i.e.
```
podman run -it --rm -p 5672:5672 -p 8161:8161 -e AMQ_USER=admin -e AMQ_PASSWORD=password -e JAVA_ARGS_APPEND=-Dwebconfig.bindings.artemis.uri=http://0.0.0.0:8161 -e AMQ_EXTRA_ARGS=--relax-jolokia --name artemis quay.io/artemiscloud/activemq-artemis-broker:artemis.2.37.0
```

**Comment by jorgecastro05** [comment]
thank you !!
