### ISSUE TITLE
Configuration address-setting type not working

### ISSUE THREAD

**Issue by braveadmin** [arkmq-org/arkmq-org-broker-image#55]
**Describe the bug**
The configuration specified in broker.xml for address-settings is not being applied to the queues matched. However, the same configuration applied directly to the queue does work.

**To Reproduce**
in broker.xml, set the following settings:

```
</address-settings>
   <address-setting match="TestAddress">
      <default-ring-size>10</default-ring-size>
   </address-setting>
</address-settings>

</addresses>
   <address name="TestAddress">
      <anycast>
         <queue name="TestQueue" />
      </anycast>
   </address>
</addresses>
```

Run the following command to get the ring-size value of TestQueue:
`curl http://localhost:8161/console/jolokia/read/org.apache.activemq.artemis:broker=!%22broker!%22,component=addresses,address=!%22TestAddress!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22TestQueue!%22/RingSize`

The value retrieved is:
```
{
    "request": {
        "mbean": "org.apache.activemq.artemis:address=\"TestAddress\",broker=\"broker\",component=addresses,queue=\"TestQueue\",routing-type=\"anycast\",subcomponent=queues",
        "attribute": "RingSize",
        "type": "read"
    },
    "value": -1,
    "timestamp": 1733990972,
    "status": 200
}
```

However, if we set the following config in broker.xml:
```
</addresses>
   <address name="TestAddress">
      <anycast>
         <queue name="TestQueue" ring-size="10" />
      </anycast>
   </address>
</addresses>
```

The value retrieved with curl command is:
```
{
    "request": {
        "mbean": "org.apache.activemq.artemis:address=\"TestAddress\",broker=\"broker\",component=addresses,queue=\"TestQueue\",routing-type=\"anycast\",subcomponent=queues",
        "attribute": "RingSize",
        "type": "read"
    },
    "value": 10,
    "timestamp": 1733991164,
    "status": 200
}
```

**Platform (please complete the following information):**
 - OS: Ubuntu
 - Version  20.04.6 LTS
 - Docker version 27.3.1, build ce12230
 - Artemis v2.38.0

**Expected behavior**
Setting the **value default-ring-size** in address-setting should make **TestQueue** to have these value.

**Additional context**
This behavior has been tested as well in a Kubernetes Environment making use of the parameters through brokerProperties as show [here](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/examples/address/artemis_broker_properties_address.yaml):
`- addressSettings.TestAddress.defaultRingSize=10`

**Comment by brusdev** [comment]
@braveadmin this issue is related to the Apache ActiveMQ Artemis project. You should subscribe to the activemq users mailing list and send an email to users@activemq.apache.org, for further details see https://activemq.apache.org/contact
